# Generated by Django 4.0.2 on 2022-02-11 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=70)),
                ('last_name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('department', models.CharField(choices=[('ENT', 'ENT'), ('Cardiology', 'Cardiology'), ('Pediatrics', 'Pediatrics'), ('Orthopedics', 'Orthopedics')], max_length=50)),
            ],
        ),
    ]
